export const ACTIONS = {
  UPDATE_SESSIONS: 'UPDATE_SESSIONS',
  UPDATE_CURRENT_SESSION: 'UPDATE_CURRENT_SESSION',
  SET_CURRENT_AUTHENTICATED_USER: 'SET_CURRENT_AUTHENTICATED_USER',
  SET_CURRENT_FIRESTORE_USER_DATA: 'SET_CURRENT_FIRESTORE_USER_DATA',
  GET_ALL_BEACHES: 'GET_ALL_BEACHES',
  GET_SESSION_ATTENDEES: 'GET_SESSION_ATTENDEES',
  GET_SESSION_MENTORS: 'GET_SESSION_MENTORS',
  GET_SINGLE_BEACH: 'GET_SINGLE_BEACH',
};
