export const ACTIONS = {
  SUBSCRIBE_TO_SESSIONS: 'SUBSCRIBE_TO_SESSIONS',
  SET_CURRENT_AUTHENTICATED_USER: 'SET_CURRENT_AUTHENTICATED_USER',
  SET_CURRENT_FIRESTORE_USER_DATA: 'SET_CURRENT_FIRESTORE_USER_DATA',
  GET_ALL_BEACHES: 'GET_ALL_BEACHES',
  GET_SESSIONS_ATTENDEES: 'GET_SESSIONS_ATTENDEES',
};
