const MIN_NUMBER_OF_VOLUNTEERS = 0;
const MAX_NUMBER_OF_VOLUNTEERS = 30;
const MIN_NUMBER_OF_REPETITIONS = 0;
const MAX_NUMBER_OF_REPETITIONS = 10;

export {
  MIN_NUMBER_OF_VOLUNTEERS,
  MAX_NUMBER_OF_VOLUNTEERS,
  MIN_NUMBER_OF_REPETITIONS,
  MAX_NUMBER_OF_REPETITIONS,
};
